import "./globals.css";
import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import NavBar from "./components/navBar";
import AuthContext, { AuthenticationContext } from "@/context/AuthContext";
import { useContext } from "react";

const inter = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContext>
          <NavBar />
          {children}
        </AuthContext>
      </body>
    </html>
  );
}
